/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-08-16 15:52:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.servlet.http.HttpSession;

public final class OrgJobs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>My Posted Jobs</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #fffaf0;\r\n");
      out.write("      font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: #d35400;\r\n");
      out.write("      margin-bottom: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .job-card {\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      border: 1px solid #f0ad4e;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      box-shadow: 0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      margin: 20px auto;\r\n");
      out.write("      max-width: 600px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h3 {\r\n");
      out.write("      color: #d35400;\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p {\r\n");
      out.write("      margin: 0 0 15px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("      padding: 10px 16px;\r\n");
      out.write("      background-color: #f39c12;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:hover {\r\n");
      out.write("      background-color: #e67e22;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Jobs You Have Posted</h1>\r\n");
      out.write("\r\n");

  String id = request.getParameter("id");
  try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hirefast", "root", "root");

      PreparedStatement statement = connection.prepareStatement("SELECT * FROM all_jobs WHERE orgId = ?");
      HttpSession session1 = request.getSession();
      statement.setInt(1, Integer.parseInt((String) session1.getAttribute("orgId")));

      ResultSet set = statement.executeQuery();

      while (set.next()) {

      out.write("\r\n");
      out.write("  <div class=\"job-card\">\r\n");
      out.write("    <h3>Title</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("title") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <h3>Job Description</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("job_description") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <h3>Role</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("role") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <h3>Salary</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("salary") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <h3>Vacancy</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("vacany") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <h3>Organisation Name</h3>\r\n");
      out.write("    <p>");
      out.print( set.getString("orgName") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"/Hirefast/JobApplicants.jsp?jobId=");
      out.print( set.getString("jobId") );
      out.write("\">View Applicants</a>\r\n");
      out.write("  </div>\r\n");

      }
      connection.close();
  } catch (Exception e) {
      e.printStackTrace();
  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
